import { MonitorPlay, Music2, ShoppingBag, Tv } from "lucide-react"

export const subscriptions = [
  {
    id: 1,
    user_id: "user1",
    subscription_name: "Netflix Premium",
    service_provider: "Netflix Inc.",
    amount: 19.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 12, 2025",
    payment_method: "Visa •••• 4242",
    reminder: true,
    active: true,
    created_at: "Jan 1, 2024",
    updated_at: "Jan 1, 2024",
    icon: MonitorPlay
  },
  {
    id: 2,
    user_id: "user1",
    subscription_name: "Spotify Family",
    service_provider: "Spotify AB",
    amount: 14.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 15, 2025",
    payment_method: "PayPal",
    reminder: false,
    active: true,
    created_at: "Jan 5, 2024",
    updated_at: "Jan 5, 2024",
    icon: Music2
  },
  {
    id: 3,
    user_id: "user1",
    subscription_name: "Amazon Prime",
    service_provider: "Amazon.com Inc.",
    amount: 139.99,
    billing_cycle: "Yearly",
    next_billing_date: "Jan 10, 2026",
    payment_method: "Mastercard •••• 5555",
    reminder: true,
    active: false,
    created_at: "Jan 10, 2024",
    updated_at: "Jan 10, 2024",
    icon: ShoppingBag
  },
  {
    id: 4,
    user_id: "user1",
    subscription_name: "Disney+",
    service_provider: "The Walt Disney Company",
    amount: 9.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 1, 2025",
    payment_method: "Apple Pay",
    reminder: true,
    active: true,
    created_at: "Jan 15, 2024",
    updated_at: "Jan 15, 2024",
    icon: Tv
  },
  {
    id: 9,
    user_id: "user1",
    subscription_name: "Disney+",
    service_provider: "The Walt Disney Company",
    amount: 9.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 1, 2025",
    payment_method: "Apple Pay",
    reminder: true,
    active: true,
    created_at: "Jan 15, 2024",
    updated_at: "Jan 15, 2024",
    icon: Tv
  },
  {
    id: 5,
    user_id: "user1",
    subscription_name: "Disney+",
    service_provider: "The Walt Disney Company",
    amount: 9.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 1, 2025",
    payment_method: "Apple Pay",
    reminder: true,
    active: true,
    created_at: "Jan 15, 2024",
    updated_at: "Jan 15, 2024",
    icon: Tv
  }, 
  {
    id: 6,
    user_id: "user1",
    subscription_name: "Disney+",
    service_provider: "The Walt Disney Company",
    amount: 9.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 1, 2025",
    payment_method: "Apple Pay",
    reminder: true,
    active: true,
    created_at: "Jan 15, 2024",
    updated_at: "Jan 15, 2024",
    icon: Tv
  },
  {
    id: 10,
    user_id: "user1",
    subscription_name: "Disney+",
    service_provider: "The Walt Disney Company",
    amount: 9.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 1, 2025",
    payment_method: "Apple Pay",
    reminder: true,
    active: true,
    created_at: "Jan 15, 2024",
    updated_at: "Jan 15, 2024",
    icon: Tv
  },
  {
    id: 11,
    user_id: "user1",
    subscription_name: "Disney+",
    service_provider: "The Walt Disney Company",
    amount: 9.99,
    billing_cycle: "Monthly",
    next_billing_date: "Feb 1, 2025",
    payment_method: "Apple Pay",
    reminder: true,
    active: true,
    created_at: "Jan 15, 2024",
    updated_at: "Jan 15, 2024",
    icon: Tv
  }
];